services:
  proxy-server:
    image: lhstack/proxy-server:latest
    container_name: proxy-server
    logging:
      options:
        max-file: '1'
        max-size: '2k'
    user: 100:100
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '256M'
    ports:
    - '8080:8080' # mkdir -p data logs
    - '3000:3000' # chown -R 100.100 data logs
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PROXY_USERNAME=admin
      - PROXY_PASSWORD=admin123